### ISSUE TITLE
fix python2 and python3 byte counts

### ISSUE THREAD

**Issue by rsha256** [rsha256/shortest-fizzbuzz#34]
In readme.md the byte count listed are incorrect and need to be fixed

**Comment by ehmsu** [comment]
May I fix this issue?

**Comment by btapash** [comment]
@rsha256  please assign this to me!

**Comment by rsha256** [comment]
@ehmsu @btapash Either if you can do it! Just make a PR and I’ll accept it, you don’t need to be assigned to fork a repo and make PRs!

**Comment by rsha256** [comment]
@btapash this is done but check out #36
